const RKEY='foodiehub_restaurant_session';
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'Request failed');return d}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function requireRestaurant(){try{const d=await api('/api/restaurant/me/');document.querySelectorAll('[data-rname]').forEach(x=>x.textContent=d.restaurant.name);return d}catch(e){location.href='login.html';throw e}}
async function logoutRestaurant(){try{await api('/api/logout/',{method:'POST'})}catch(e){}localStorage.removeItem(RKEY);localStorage.removeItem('foodiehub_session');location.href='login.html'}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('logout')?.addEventListener('click',logoutRestaurant)});
async function loadDashboard(){try{const d=await requireRestaurant();document.getElementById('restaurantName').textContent=d.restaurant.name;document.getElementById('menu').textContent=d.stats.menu_items;document.getElementById('orders').textContent=d.stats.orders;document.getElementById('pendingOrders').textContent=d.stats.pending_orders;document.getElementById('reservations').textContent=d.stats.reservations;document.getElementById('account').innerHTML=`<b>${esc(d.user.name)}</b><br>${esc(d.user.email)}<br>${esc(d.restaurant.location||'')}`}catch(e){console.error(e)}}
async function loadMenu(){try{await requireRestaurant();const d=await api('/api/restaurant/menu/');const el=document.getElementById('rows');el.innerHTML=d.items.map(i=>`<tr><td><b>${esc(i.name)}</b><div class="small">${esc(i.description)}</div></td><td>${esc(i.category||'Other')}</td><td>₹${Number(i.price).toLocaleString('en-IN')}</td><td><button class="status ${i.available?'on':'off'}" onclick="toggleMenu(${i.id},${!i.available})">${i.available?'Available':'Unavailable'}</button></td><td><button class="btn" onclick="editMenu(${i.id})">Edit</button> <button class="btn danger" onclick="deleteMenu(${i.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No menu items yet.</td></tr>'}catch(e){document.getElementById('rows').innerHTML=`<tr><td colspan="5">${esc(e.message)}</td></tr>`}}
async function addMenu(e){e.preventDefault();try{const body=new URLSearchParams({name:mName.value.trim(),category:mCategory.value.trim(),description:mDescription.value.trim(),price:mPrice.value,image:mImage.value.trim(),available:'true'});await api('/api/restaurant/menu/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});e.target.reset();loadMenu()}catch(err){alert(err.message)}}
async function toggleMenu(id,val){try{await api('/api/restaurant/menu/'+id+'/',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({available:val})});loadMenu()}catch(e){alert(e.message)}}
async function editMenu(id){const price=prompt('New price:');if(price===null)return;try{await api('/api/restaurant/menu/'+id+'/',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({price})});loadMenu()}catch(e){alert(e.message)}}
async function deleteMenu(id){if(!confirm('Delete this menu item?'))return;try{await api('/api/restaurant/menu/'+id+'/',{method:'DELETE'});loadMenu()}catch(e){alert(e.message)}}
async function loadOrders(){try{await requireRestaurant();const d=await api('/api/restaurant/orders/');const el=document.getElementById('rows');el.innerHTML=d.orders.map(o=>`<tr><td>#${o.id}</td><td><b>${esc(o.name)}</b><div class="small">${esc(o.phone)} · ${esc(o.address)}</div></td><td>${o.items.map(i=>`${esc(i.name)} × ${i.quantity}`).join('<br>')}</td><td>₹${Number(o.total).toLocaleString('en-IN')}</td><td><select onchange="setOrder(${o.id},this.value)">${['placed','confirmed','preparing','ready','out_for_delivery','delivered','cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="5">No orders yet.</td></tr>'}catch(e){document.getElementById('rows').innerHTML=`<tr><td colspan="5">${esc(e.message)}</td></tr>`}}
async function setOrder(id,status){try{await api('/api/restaurant/orders/'+id+'/',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})}catch(e){alert(e.message)}}
async function loadReservations(){try{await requireRestaurant();const d=await api('/api/restaurant/reservations/');const el=document.getElementById('cards');el.innerHTML=d.reservations.map(r=>`<article class="card"><div class="cardhead"><div><h2>#${r.id} · ${esc(r.name)}</h2><div class="small">${esc(r.email)} · ${esc(r.phone)}</div></div><select onchange="setReservation(${r.id},this.value)">${['pending','confirmed','completed','cancelled'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></div><p><b>${esc(r.date)}</b> at <b>${esc(r.time)}</b> · ${r.guests} guest${r.guests==1?'':'s'}</p><div class="small">${r.message?esc(r.message):'No message'}</div><div class="prebook">${r.items.length?r.items.map(i=>`${esc(i.name)} × ${i.quantity}`).join(' · '):'No pre-booked food'} ${r.prebook_total?`<b>· ₹${Number(r.prebook_total).toLocaleString('en-IN')}</b>`:''}</div></article>`).join('')||'<div class="card">No reservations yet.</div>'}catch(e){document.getElementById('cards').innerHTML=`<div class="card">${esc(e.message)}</div>`}}
async function setReservation(id,status){try{await api('/api/restaurant/reservations/'+id+'/',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})}catch(e){alert(e.message)}}
async function loadInventory(){try{await requireRestaurant();const d=await api('/api/restaurant/inventory/');const el=document.getElementById('rows');el.innerHTML=d.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.quantity} ${esc(i.unit)}</td><td>${i.reorder_level}</td><td>${i.quantity<=i.reorder_level?'<span class="warn">Low stock</span>':'<span class="ok">Healthy</span>'}</td><td><button class="btn danger" onclick="deleteInventory(${i.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No inventory items yet.</td></tr>'}catch(e){document.getElementById('rows').innerHTML=`<tr><td colspan="5">${esc(e.message)}</td></tr>`}}
async function addInventory(e){e.preventDefault();try{const body=new URLSearchParams({name:iName.value.trim(),quantity:iQty.value,unit:iUnit.value,reorder_level:iReorder.value});await api('/api/restaurant/inventory/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});e.target.reset();loadInventory()}catch(err){alert(err.message)}}
async function deleteInventory(id){if(!confirm('Delete this inventory item?'))return;try{await api('/api/restaurant/inventory/'+id+'/',{method:'DELETE'});loadInventory()}catch(e){alert(e.message)}}
