from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.register_user),
    path("login/", views.login_user),
    path("admin-register/", views.admin_register),
    path("restaurant-register/", views.restaurant_register),
    path("restaurant-login/", views.restaurant_login),
    path("restaurant/me/", views.restaurant_me),
    path("restaurant/dashboard/", views.restaurant_dashboard),
    path("restaurant/menu/", views.restaurant_menu),
    path("restaurant/menu/<int:item_id>/", views.restaurant_menu_item),
    path("restaurant/orders/", views.restaurant_orders),
    path("restaurant/orders/<int:order_id>/", views.restaurant_order_detail),
    path("restaurant/reservations/", views.restaurant_reservations),
    path("restaurant/reservations/<int:reservation_id>/", views.restaurant_reservation_detail),
    path("restaurant/inventory/", views.restaurant_inventory),
    path("restaurant/inventory/<int:item_id>/", views.restaurant_inventory_item),
    path("admin-login/", views.admin_login),
    path("logout/", views.logout_user),
    path("me/", views.current_user),
    path("forgot-password/", views.forgot_password),
    path("reset-password/", views.reset_password),
    path("restaurants/", views.restaurants),
    path("menu-items/", views.menu_items),
    path("restaurants/<int:restaurant_id>/", views.restaurant_detail),
    path("reservations/", views.create_reservation),
    path("reservations/history/", views.reservation_history),
    path("orders/", views.create_order),
    path("orders/history/", views.order_history),
]
