from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.register_user),
    path("login/", views.login_user),
    path("admin-register/", views.admin_register),
    path("restaurant-register/", views.restaurant_register),
    path("restaurant-login/", views.restaurant_login),
    path("restaurant/me/", views.restaurant_me),
    path("restaurant/dashboard/", views.restaurant_dashboard),
    path("restaurant/menu/", views.restaurant_menu),
    path("restaurant/menu/<int:item_id>/", views.restaurant_menu_item),
    path("restaurant/orders/", views.restaurant_orders),
    path("restaurant/orders/<int:order_id>/", views.restaurant_order_detail),
    path("restaurant/reservations/", views.restaurant_reservations),
    path("restaurant/reservations/<int:reservation_id>/", views.restaurant_reservation_detail),
    path("restaurant/inventory/", views.restaurant_inventory),
    path("restaurant/inventory/<int:item_id>/", views.restaurant_inventory_item),
    path("admin-login/", views.admin_login),
    path("logout/", views.logout_user),
    path("me/", views.current_user),
    path("contact/", views.submit_contact_message),
    path("admin/contact-messages/", views.admin_contact_messages),
    path("admin/contact-messages/<int:message_id>/read/", views.admin_mark_contact_message_read),
    path("profile/update/", views.update_profile),
    path("profile/change-password/", views.change_password),
    path("forgot-password/", views.forgot_password),
    path("reset-password/", views.reset_password),
    path("restaurants/", views.restaurants),
    path("menu-items/", views.menu_items),
    path("restaurants/<int:restaurant_id>/", views.restaurant_detail),
    path("reservations/", views.create_reservation),
    path("reservations/history/", views.reservation_history),
    path("notifications/push/public-key/", views.push_public_key),
    path("notifications/push/subscribe/", views.push_subscribe),
    path("notifications/push/unsubscribe/", views.push_unsubscribe),
    path("reservations/attendance/<int:reservation_id>/<str:token>/coming/", views.reservation_attendance_response, {"response": "coming"}),
    path("reservations/attendance/<int:reservation_id>/<str:token>/not-coming/", views.reservation_attendance_response, {"response": "not-coming"}),
    path("orders/", views.create_order),
    path("orders/history/", views.order_history),
    path("orders/<int:order_id>/tracking/", views.order_tracking, name="order-tracking"),
    path("reservations/<int:reservation_id>/payment-status/", views.reservation_payment_status),
    path("reservations/<int:reservation_id>/pay-remaining/", views.pay_reservation_remaining),
    path("reservations/<int:reservation_id>/refund/", views.process_reservation_refund),
    path("reservations/preorder-payment/", views.create_reservation_upfront_payment),
    path("payments/config/", views.payment_config, name="payment-config"),
    path("payments/demo/", views.create_demo_payment, name="demo-payment"),
    path("payments/razorpay/create-order/", views.create_razorpay_order),
    path("payments/razorpay/verify/", views.verify_razorpay_payment),
    path("payments/razorpay/failed/", views.mark_razorpay_payment_failed),
    path("auth/google/", views.google_login),
    path("auth/config/", views.google_auth_config),
    path("delivery/register/", views.delivery_register),
    path("delivery-login/", views.delivery_login),
    path("delivery/me/", views.delivery_me),
    path("delivery/dashboard/", views.delivery_dashboard, name="delivery-dashboard"),
    path("delivery/availability/", views.delivery_toggle_availability),
    path("delivery/orders/<int:order_id>/accept/", views.delivery_accept_order),
    path("delivery/orders/<int:order_id>/status/", views.delivery_update_status, name="delivery-status"),
    path("delivery/orders/<int:order_id>/location/", views.delivery_update_location, name="delivery-location"),
    path("delivery/available/", views.delivery_available_partners),
    path("admin/delivery/partners/", views.admin_delivery_partners),
    path("admin/delivery/assign/", views.admin_assign_delivery),
    path("admin/orders/", views.admin_orders),
]
