-- FoodieHub local image mapping
-- Safe to run after the restaurant/menu seed data has been imported.
-- All paths are served by Django from frontend/images.

START TRANSACTION;

UPDATE restaurant_restaurant SET image='/images/restaurants/v-grand-family-restaurant.svg' WHERE name='V Grand Family Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/hotel-paradise.svg' WHERE name='Hotel Paradise';
UPDATE restaurant_restaurant SET image='/images/restaurants/prakriti-multicuisine-restaurant.svg' WHERE name='Prakriti Multicuisine Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/bilal-multi-cuisine-restaurant.svg' WHERE name='Bilal Multi Cuisine Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/alif-hyderabad-kachi-dum-biryani.svg' WHERE name='Alif Hyderabad Kachi Dum Biryani';
UPDATE restaurant_restaurant SET image='/images/restaurants/bismillah-hyderabad-dum-biryani.svg' WHERE name='Bismillah Hyderabad Dum Biryani';
UPDATE restaurant_restaurant SET image='/images/restaurants/vicky-micky-kitchen-family-restaurant.svg' WHERE name='Vicky Micky Kitchen Family Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/kritunga.svg' WHERE name='Kritunga';
UPDATE restaurant_restaurant SET image='/images/restaurants/r-r-garden-restaurant.svg' WHERE name='R R Garden Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/sri-himaja-tiffins-and-catering.svg' WHERE name='Sri Himaja Tiffins and Catering';
UPDATE restaurant_restaurant SET image='/images/restaurants/lasya-grand-restaurant.svg' WHERE name='Lasya Grand Restaurant';
UPDATE restaurant_restaurant SET image='/images/restaurants/ismail-biryani.svg' WHERE name='Ismail Biryani';
UPDATE restaurant_restaurant SET image='/images/restaurants/lakshmi-pulka-point.svg' WHERE name='Lakshmi Pulka Point';
UPDATE restaurant_restaurant SET image='/images/restaurants/rs-punjabi-family-dabha-gardens.svg' WHERE name='RS Punjabi Family Dabha Gardens';
UPDATE restaurant_restaurant SET image='/images/restaurants/hotel-sarovar.svg' WHERE name='Hotel Sarovar';
UPDATE restaurant_restaurant SET image='/images/restaurants/mawa-s-kitchen.svg' WHERE name='Mawa''s Kitchen';
UPDATE restaurant_restaurant SET image='/images/restaurants/gita-s-kitchen.svg' WHERE name='Gita''s Kitchen';
UPDATE restaurant_restaurant SET image='/images/restaurants/hoskote-4-am-biryani.svg' WHERE name='Hoskote 4 AM Biryani';
UPDATE restaurant_restaurant SET image='/images/restaurants/avula-vari-vindhu-bhojanam.svg' WHERE name='Avula Vari Vindhu Bhojanam';
UPDATE restaurant_restaurant SET image='/images/restaurants/sai-fast-foods.svg' WHERE name='Sai Fast Foods';
UPDATE restaurant_restaurant SET image='/images/restaurants/spice-symphony.svg' WHERE name='Spice Symphony';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/v-grand-family-restaurant--veg-sweet-corn-soup.svg' WHERE r.name='V Grand Family Restaurant' AND m.name='Veg Sweet Corn Soup';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/v-grand-family-restaurant--veg-hot-and-sour-soup.svg' WHERE r.name='V Grand Family Restaurant' AND m.name='Veg Hot & Sour Soup';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/v-grand-family-restaurant--veg-dragon-soup.svg' WHERE r.name='V Grand Family Restaurant' AND m.name='Veg Dragon Soup';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/v-grand-family-restaurant--veg-manchow-soup.svg' WHERE r.name='V Grand Family Restaurant' AND m.name='Veg Manchow Soup';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/v-grand-family-restaurant--veg-noodles.svg' WHERE r.name='V Grand Family Restaurant' AND m.name='Veg Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--mushroom-biryani.svg' WHERE r.name='Hotel Paradise' AND m.name='Mushroom Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--mutton-biryani.svg' WHERE r.name='Hotel Paradise' AND m.name='Mutton Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--fish-biryani.svg' WHERE r.name='Hotel Paradise' AND m.name='Fish Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--prawns-biryani.svg' WHERE r.name='Hotel Paradise' AND m.name='Prawns Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--paneer-biryani.svg' WHERE r.name='Hotel Paradise' AND m.name='Paneer Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--chicken-tikka.svg' WHERE r.name='Hotel Paradise' AND m.name='Chicken Tikka';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--tandoori-chicken.svg' WHERE r.name='Hotel Paradise' AND m.name='Tandoori Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-paradise--paneer-butter-masala.svg' WHERE r.name='Hotel Paradise' AND m.name='Paneer Butter Masala';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/prakriti-multicuisine-restaurant--veg-biryani.svg' WHERE r.name='Prakriti Multicuisine Restaurant' AND m.name='Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/prakriti-multicuisine-restaurant--chicken-biryani.svg' WHERE r.name='Prakriti Multicuisine Restaurant' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/prakriti-multicuisine-restaurant--paneer-chilli.svg' WHERE r.name='Prakriti Multicuisine Restaurant' AND m.name='Paneer Chilli';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/prakriti-multicuisine-restaurant--gobi-manchurian.svg' WHERE r.name='Prakriti Multicuisine Restaurant' AND m.name='Gobi Manchurian';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/prakriti-multicuisine-restaurant--chicken-noodles.svg' WHERE r.name='Prakriti Multicuisine Restaurant' AND m.name='Chicken Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bilal-multi-cuisine-restaurant--butter-chicken.svg' WHERE r.name='Bilal Multi Cuisine Restaurant' AND m.name='Butter Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bilal-multi-cuisine-restaurant--chicken-tikka-masala.svg' WHERE r.name='Bilal Multi Cuisine Restaurant' AND m.name='Chicken Tikka Masala';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bilal-multi-cuisine-restaurant--chicken-cheese-burger.svg' WHERE r.name='Bilal Multi Cuisine Restaurant' AND m.name='Chicken Cheese Burger';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bilal-multi-cuisine-restaurant--special-chicken-biryani-family-pack.svg' WHERE r.name='Bilal Multi Cuisine Restaurant' AND m.name='Special Chicken Biryani Family Pack';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bilal-multi-cuisine-restaurant--paneer-tikka.svg' WHERE r.name='Bilal Multi Cuisine Restaurant' AND m.name='Paneer Tikka';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/alif-hyderabad-kachi-dum-biryani--chicken-dum-biryani.svg' WHERE r.name='Alif Hyderabad Kachi Dum Biryani' AND m.name='Chicken Dum Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/alif-hyderabad-kachi-dum-biryani--chicken-fry-biryani.svg' WHERE r.name='Alif Hyderabad Kachi Dum Biryani' AND m.name='Chicken Fry Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/alif-hyderabad-kachi-dum-biryani--chicken-dum-biryani-family-pack.svg' WHERE r.name='Alif Hyderabad Kachi Dum Biryani' AND m.name='Chicken Dum Biryani Family Pack';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/alif-hyderabad-kachi-dum-biryani--chicken-dum-biryani-2-piece.svg' WHERE r.name='Alif Hyderabad Kachi Dum Biryani' AND m.name='Chicken Dum Biryani 2 Piece';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/alif-hyderabad-kachi-dum-biryani--gongura-chicken-biryani.svg' WHERE r.name='Alif Hyderabad Kachi Dum Biryani' AND m.name='Gongura Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bismillah-hyderabad-dum-biryani--chicken-dum-biryani.svg' WHERE r.name='Bismillah Hyderabad Dum Biryani' AND m.name='Chicken Dum Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bismillah-hyderabad-dum-biryani--chicken-fry-biryani.svg' WHERE r.name='Bismillah Hyderabad Dum Biryani' AND m.name='Chicken Fry Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bismillah-hyderabad-dum-biryani--mutton-biryani.svg' WHERE r.name='Bismillah Hyderabad Dum Biryani' AND m.name='Mutton Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bismillah-hyderabad-dum-biryani--egg-biryani.svg' WHERE r.name='Bismillah Hyderabad Dum Biryani' AND m.name='Egg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/bismillah-hyderabad-dum-biryani--chicken-65.svg' WHERE r.name='Bismillah Hyderabad Dum Biryani' AND m.name='Chicken 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--chicken-dum-biryani.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Chicken Dum Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--chicken-fry-biryani.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Chicken Fry Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--bagara-rice.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Bagara Rice';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--fish-biryani.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Fish Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--prawns-biryani.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Prawns Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--andhra-chicken.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Andhra Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--chicken-curry.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Chicken Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/vicky-micky-kitchen-family-restaurant--paneer-65.svg' WHERE r.name='Vicky Micky Kitchen Family Restaurant' AND m.name='Paneer 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/kritunga--andhra-meals.svg' WHERE r.name='Kritunga' AND m.name='Andhra Meals';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/kritunga--chicken-biryani.svg' WHERE r.name='Kritunga' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/kritunga--mutton-biryani.svg' WHERE r.name='Kritunga' AND m.name='Mutton Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/kritunga--paneer-curry.svg' WHERE r.name='Kritunga' AND m.name='Paneer Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/kritunga--chicken-fry.svg' WHERE r.name='Kritunga' AND m.name='Chicken Fry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--kaju-biryani.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Kaju Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--special-veg-biryani.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Special Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--kaju-paneer-biryani.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Kaju Paneer Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--rr-special-biryani.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Rr Special Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--gobi-65.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Gobi 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--paneer-65.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Paneer 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--pulka.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Pulka';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/r-r-garden-restaurant--rumali-roti.svg' WHERE r.name='R R Garden Restaurant' AND m.name='Rumali Roti';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sri-himaja-tiffins-and-catering--upma-dosa.svg' WHERE r.name='Sri Himaja Tiffins and Catering' AND m.name='Upma Dosa';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sri-himaja-tiffins-and-catering--idly.svg' WHERE r.name='Sri Himaja Tiffins and Catering' AND m.name='Idly';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sri-himaja-tiffins-and-catering--masala-dosa.svg' WHERE r.name='Sri Himaja Tiffins and Catering' AND m.name='Masala Dosa';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sri-himaja-tiffins-and-catering--vada.svg' WHERE r.name='Sri Himaja Tiffins and Catering' AND m.name='Vada';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sri-himaja-tiffins-and-catering--poori.svg' WHERE r.name='Sri Himaja Tiffins and Catering' AND m.name='Poori';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--paneer-pulao.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Paneer Pulao';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--mushroom-pulao.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Mushroom Pulao';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--kaju-pulao.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Kaju Pulao';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--chicken-pulao.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Chicken Pulao';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--prawns-pulao.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Prawns Pulao';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--chicken-65.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Chicken 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--masala-kulcha.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Masala Kulcha';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lasya-grand-restaurant--pulka.svg' WHERE r.name='Lasya Grand Restaurant' AND m.name='Pulka';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/ismail-biryani--chicken-biryani.svg' WHERE r.name='Ismail Biryani' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/ismail-biryani--mutton-biryani.svg' WHERE r.name='Ismail Biryani' AND m.name='Mutton Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/ismail-biryani--egg-biryani.svg' WHERE r.name='Ismail Biryani' AND m.name='Egg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/ismail-biryani--chicken-65.svg' WHERE r.name='Ismail Biryani' AND m.name='Chicken 65';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/ismail-biryani--chicken-fry.svg' WHERE r.name='Ismail Biryani' AND m.name='Chicken Fry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lakshmi-pulka-point--chicken-curry.svg' WHERE r.name='Lakshmi Pulka Point' AND m.name='Chicken Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lakshmi-pulka-point--andhra-chicken.svg' WHERE r.name='Lakshmi Pulka Point' AND m.name='Andhra Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lakshmi-pulka-point--maharani-chicken.svg' WHERE r.name='Lakshmi Pulka Point' AND m.name='Maharani Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lakshmi-pulka-point--punjabi-chicken.svg' WHERE r.name='Lakshmi Pulka Point' AND m.name='Punjabi Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/lakshmi-pulka-point--pulka.svg' WHERE r.name='Lakshmi Pulka Point' AND m.name='Pulka';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--boneless-andhra-chicken-curry.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Boneless Andhra Chicken Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--kadai-chicken.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Kadai Chicken';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--egg-biryani.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Egg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--kaju-curry.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Kaju Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--dal-fry.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Dal Fry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--chicken-lollipop-biryani.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Chicken Lollipop Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/rs-punjabi-family-dabha-gardens--veg-biryani.svg' WHERE r.name='RS Punjabi Family Dabha Gardens' AND m.name='Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-sarovar--chicken-biryani.svg' WHERE r.name='Hotel Sarovar' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-sarovar--veg-biryani.svg' WHERE r.name='Hotel Sarovar' AND m.name='Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-sarovar--masala-dosa.svg' WHERE r.name='Hotel Sarovar' AND m.name='Masala Dosa';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-sarovar--idly.svg' WHERE r.name='Hotel Sarovar' AND m.name='Idly';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hotel-sarovar--paneer-curry.svg' WHERE r.name='Hotel Sarovar' AND m.name='Paneer Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/mawa-s-kitchen--chicken-biryani.svg' WHERE r.name='Mawa''s Kitchen' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/mawa-s-kitchen--paneer-butter-masala.svg' WHERE r.name='Mawa''s Kitchen' AND m.name='Paneer Butter Masala';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/mawa-s-kitchen--chicken-noodles.svg' WHERE r.name='Mawa''s Kitchen' AND m.name='Chicken Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/mawa-s-kitchen--veg-manchurian.svg' WHERE r.name='Mawa''s Kitchen' AND m.name='Veg Manchurian';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/mawa-s-kitchen--garlic-naan.svg' WHERE r.name='Mawa''s Kitchen' AND m.name='Garlic Naan';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/gita-s-kitchen--chicken-biryani.svg' WHERE r.name='Gita''s Kitchen' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/gita-s-kitchen--veg-biryani.svg' WHERE r.name='Gita''s Kitchen' AND m.name='Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/gita-s-kitchen--chilli-paneer.svg' WHERE r.name='Gita''s Kitchen' AND m.name='Chilli Paneer';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/gita-s-kitchen--chicken-manchurian.svg' WHERE r.name='Gita''s Kitchen' AND m.name='Chicken Manchurian';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/gita-s-kitchen--paneer-curry.svg' WHERE r.name='Gita''s Kitchen' AND m.name='Paneer Curry';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hoskote-4-am-biryani--mutton-dum-biryani-1000ml.svg' WHERE r.name='Hoskote 4 AM Biryani' AND m.name='Mutton Dum Biryani 1000ml';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hoskote-4-am-biryani--chicken-dum-biryani.svg' WHERE r.name='Hoskote 4 AM Biryani' AND m.name='Chicken Dum Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hoskote-4-am-biryani--chicken-fry-biryani.svg' WHERE r.name='Hoskote 4 AM Biryani' AND m.name='Chicken Fry Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hoskote-4-am-biryani--chicken-kebab.svg' WHERE r.name='Hoskote 4 AM Biryani' AND m.name='Chicken Kebab';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/hoskote-4-am-biryani--egg-biryani.svg' WHERE r.name='Hoskote 4 AM Biryani' AND m.name='Egg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--dry-fruit-milk-shake.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Dry Fruit Milk Shake';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--oreo-milk-shake.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Oreo Milk Shake';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--mashroom-masala-dosa.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Mashroom Masala Dosa';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--parota.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Parota';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--chapathi.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Chapathi';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--curd-rice.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Curd Rice';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/avula-vari-vindhu-bhojanam--plain-roti.svg' WHERE r.name='Avula Vari Vindhu Bhojanam' AND m.name='Plain Roti';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sai-fast-foods--veg-fried-rice.svg' WHERE r.name='Sai Fast Foods' AND m.name='Veg Fried Rice';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sai-fast-foods--chicken-fried-rice.svg' WHERE r.name='Sai Fast Foods' AND m.name='Chicken Fried Rice';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sai-fast-foods--veg-noodles.svg' WHERE r.name='Sai Fast Foods' AND m.name='Veg Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sai-fast-foods--chicken-noodles.svg' WHERE r.name='Sai Fast Foods' AND m.name='Chicken Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/sai-fast-foods--gobi-manchurian.svg' WHERE r.name='Sai Fast Foods' AND m.name='Gobi Manchurian';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--cheese-pizza.svg' WHERE r.name='Spice Symphony' AND m.name='Cheese Pizza';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--veg-pizza.svg' WHERE r.name='Spice Symphony' AND m.name='Veg Pizza';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--chicken-burger.svg' WHERE r.name='Spice Symphony' AND m.name='Chicken Burger';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--veg-burger.svg' WHERE r.name='Spice Symphony' AND m.name='Veg Burger';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--chicken-biryani.svg' WHERE r.name='Spice Symphony' AND m.name='Chicken Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--veg-biryani.svg' WHERE r.name='Spice Symphony' AND m.name='Veg Biryani';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--idly.svg' WHERE r.name='Spice Symphony' AND m.name='Idly';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--paneer-butter-masala.svg' WHERE r.name='Spice Symphony' AND m.name='Paneer Butter Masala';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--chicken-noodles.svg' WHERE r.name='Spice Symphony' AND m.name='Chicken Noodles';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--fresh-juice.svg' WHERE r.name='Spice Symphony' AND m.name='Fresh Juice';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--chocolate-milkshake.svg' WHERE r.name='Spice Symphony' AND m.name='Chocolate Milkshake';
UPDATE restaurant_menuitem m JOIN restaurant_restaurant r ON r.id=m.restaurant_id SET m.image='/images/menu/spice-symphony--ice-cream.svg' WHERE r.name='Spice Symphony' AND m.name='Ice Cream';

COMMIT;

-- Verification
SELECT COUNT(*) AS restaurants_with_images FROM restaurant_restaurant WHERE image LIKE '/images/restaurants/%';
SELECT COUNT(*) AS menu_items_with_images FROM restaurant_menuitem WHERE image LIKE '/images/menu/%';
