# Generated by Django 4.2.30 on 2026-10-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delivery_google_tracking'),
        ('restaurant', '0005_restaurant_owner'),
    ]

    operations = [
    ]
