# Generated by Django 4.2.30 on 2026-10-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_payment_method'),
        ('restaurant', '0008_alter_order_payment_method'),
    ]

    operations = [
    ]
