# Generated by Django 4.2.30 on 2026-10-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_merge_20261005_1806'),
        ('restaurant', '0010_pushsubscription'),
    ]

    operations = [
    ]
