const api=async(u,o={})=>{const r=await fetch(u,{credentials:"same-origin",cache:"no-store",...o});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||"Request failed");return d};
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function money(v){return "₹"+Number(v||0).toLocaleString("en-IN")}
let watchId=null, activeOrder=null;
async function load(){try{const me=await api("/api/delivery/me/");const av=document.getElementById("availability");if(av){av.textContent=me.partner.is_available?"Available for orders":"Offline";av.className="btn "+(me.partner.is_available?"orange":"");av.onclick=async()=>{try{const n=await api("/api/delivery/availability/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_available:!me.partner.is_available})});av.textContent=n.is_available?"Available for orders":"Offline";av.className="btn "+(n.is_available?"orange":"")}catch(e){alert(e.message)}}}const d=await api("/api/delivery/dashboard/");const active=document.getElementById("active");const available=document.getElementById("available");active.innerHTML=(d.active_orders||[]).map(o=>`<article class="card"><div class="cardhead"><div><h2>Order #${o.id}</h2><div class="small">${esc(o.name)} · ${esc(o.phone)}</div></div><span class="badge orange">${esc(o.status)}</span></div><p><b>Deliver to:</b> ${esc(o.address)}, ${esc(o.city)} - ${esc(o.pincode)}</p><p>${o.items.map(i=>esc(i.name)+" × "+i.quantity).join(" · ")}</p><div class="top-actions"><button class="btn orange" onclick="startTrip(${o.id})">Start / Resume GPS</button><button class="btn" onclick="setStatus(${o.id},'picked_up')">Picked up</button><button class="btn" onclick="setStatus(${o.id},'delivered')">Delivered</button></div></article>`).join("")||'<div class="card empty">No active delivery.</div>';
available.innerHTML=(d.available_orders||[]).map(o=>`<article class="card"><div class="cardhead"><div><h2>Order #${o.id}</h2><div class="small">${esc(o.name)}</div></div><b>${money(o.total)}</b></div><p>${esc(o.address)}, ${esc(o.city)} - ${esc(o.pincode)}</p><button class="btn orange" onclick="acceptOrder(${o.id})">Accept delivery</button></article>`).join("")||'<div class="card empty">No ready orders waiting.</div>';if(d.active_orders?.[0]) startTrip(d.active_orders[0].id)}catch(e){document.getElementById("active").innerHTML='<div class="card">'+esc(e.message)+'</div>'}}
async function acceptOrder(id){try{await api("/api/delivery/orders/"+id+"/accept/",{method:"POST"});load()}catch(e){alert(e.message)}}
async function setStatus(id,status){try{await api("/api/delivery/orders/"+id+"/status/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load()}catch(e){alert(e.message)}}
function startTrip(id){activeOrder=id;if(!navigator.geolocation){alert("GPS is not available in this browser.");return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(async p=>{try{await api("/api/delivery/orders/"+id+"/location/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lat:p.coords.latitude,lng:p.coords.longitude})});document.getElementById("gpsStatus").textContent="GPS sharing active · "+p.coords.latitude.toFixed(5)+", "+p.coords.longitude.toFixed(5)}catch(e){console.error(e)}},e=>document.getElementById("gpsStatus").textContent="GPS error: "+e.message,{enableHighAccuracy:true,maximumAge:5000,timeout:10000})}
document.getElementById("logout")?.addEventListener("click",async()=>{try{await api("/api/logout/",{method:"POST"})}catch(_){}location.href="login.html"});document.addEventListener("DOMContentLoaded",load);